FROM centos:7
MAINTAINER uryyyyyyy <koki305@gmail.com>
RUN yum update -y
RUN yum clean all
RUN yum install tcl gcc wget make vim net-tools -y
RUN yum install 

CMD [ "/bin/bash" ]

#yum install -y epel-release
#yum install libev libev-devel -y
